import { makeLocalUrl } from './getDocUrl';


export const fakeDocumentsData = [
	{ id: 1, name: 'Other', type: "pdf", path: makeLocalUrl("/6f90e723-1dd0-4415-9536-ad16f312aa03.pdf") },
	{ id: 2, name: 'OSFC plukk list', type: "pdf", path: makeLocalUrl("/3bb7a5a2-ad5e-4445-8f78-4c12253f2d09.pdf") },
	{ id: 3, name: 'SAD', type: "pdf", path: makeLocalUrl("/3bb7a5a2-ad5e-4445-8f78-4c12253f2d09.pdf") },
	{ id: 4, name: 'Label', type: "pdf", path: makeLocalUrl("/6f90e723-1dd0-4415-9536-ad16f312aa03.pdf") },
	{ id: 5, name: 'Deviation report', type: "image", path: makeLocalUrl("/bb5a3d67-ff85-4ca6-96c9-a3e711341540.png") },
	{ id: 6, name: 'Off loading chart', type: "image", path: makeLocalUrl("/bb5a3d67-ff85-4ca6-96c9-a3e711341540.png") },
	{ id: 7, name: 'MIO', type: "image", path: makeLocalUrl("/bb5a3d67-ff85-4ca6-96c9-a3e711341540.png") },
	{ id: 8, name: 'Invoice', type: "image", path: makeLocalUrl("/d34033be-8ef9-41d4-b64b-5ad0c451fce3.png") },
	{ id: 9, name: 'Export documents', type: "pdf", path: makeLocalUrl("/a1231723-1dd0-4415-9536-ad16f312aa03.pdf") },
	{ id: 10, name: 'CMR', type: "pdf", path: makeLocalUrl("/a1231723-1dd0-4415-9536-ad16f312aa03.pdf") },
];

export const initialFakeDocumentsData = fakeDocumentsData.slice(2);

export const fakeOrdersData = [
	{
		"customer": "Blue Water Shipping AS",
		"reference": "df13123123",
		"service": "Reload Car - Terminal - Car",
		"status": "ON HOLD",
		"priority": "YES",
		"autocomplete": "NO",
		"terminal": "OSLO",
		"eta_a_date": "24-10-20",
		"eta_a_time": "10:00",
		"eta_a_slot_time": "16:00",
		"port_in": "Station",
		"eta_a_3rd_party": "North",
		"place_from": "Mikolow",
		"eta_a_show_docs": "YES",
		"eta_a_driver": "-",
		"eta_a_driver_phone": "09183133131",
		"eta_a_truck": "-",
		"eta_a_trailer": "ASD1313",
		"eta_d_date": "24-10-20",
		"eta_d_time": "10:00",
		"eta_d_slot_time": "16:00",
		"port_out": "Station",
		"eta_d_3rd_party": "North",
		"place_to": "Mikolow",
		"eta_d_show_docs": "YES",
		"eta_d_driver": "-",
		"eta_d_driver_phone": "-",
		"eta_d_truck": "-",
		"eta_d_trailer": "-",
		"split_load": "NO",
		"trip_no": "13123",
		"loading_no": "13123",
		"etra_loading_time": "23",
		"plumb_seal": "YES",
		"plumb_number": "2131231",
		"is_etra_time_billable": "YES",
		"area": "WOLK",
		"label_source": "NONE",
		"label": "-"
	},
	{
		"customer": "Grieg SeaFood",
		"reference": "df456789",
		"service": "Unload Truck - Warehouse - Forklift",
		"status": "ORDER COMPLETED",
		"priority": "NO",
		"autocomplete": "YES",
		"terminal": "STOCKHOLM",
		"eta_a_date": "25-10-20",
		"eta_a_time": "12:30",
		"eta_a_slot_time": "18:00",
		"port_in": "Warehouse",
		"eta_a_3rd_party": "South",
		"place_from": "Gdansk",
		"eta_a_show_docs": "NO",
		"eta_a_driver": "-",
		"eta_a_driver_phone": "-",
		"eta_a_truck": "asd13133",
		"eta_a_trailer": "ASD1313",
		"eta_d_date": "26-10-20",
		"eta_d_time": "08:00",
		"eta_d_slot_time": "14:30",
		"port_out": "Warehouse",
		"eta_d_3rd_party": "South",
		"place_to": "Warsaw",
		"eta_d_show_docs": "YES",
		"eta_d_driver": "-",
		"eta_d_driver_phone": "-",
		"eta_d_truck": "-",
		"eta_d_trailer": "-",
		"split_load": "YES",
		"trip_no": "98765",
		"loading_no": "98765",
		"etra_loading_time": "1",
		"is_area_blocked": "NO",
		"plumb_seal": "NO",
		"plumb_number": "987654",
		"is_etra_time_billable": "NO",
		"area": "STOCK",
		"label_source": "WAREHOUSE",
		"label": "LABEL123"
	},
	{
		"customer": "Born",
		"reference": "df789012",
		"service": "Ship Container - Port - Crane",
		"status": "DELIVERED",
		"priority": "YES",
		"autocomplete": "NO",
		"terminal": "COPENHAGEN",
		"eta_a_date": "27-10-20",
		"eta_a_time": "14:00",
		"eta_a_slot_time": "20:00",
		"port_in": "Port",
		"eta_a_3rd_party": "East",
		"place_from": "Oslo",
		"eta_a_show_docs": "YES",
		"eta_a_driver": "Holy",
		"eta_a_driver_phone": "-",
		"eta_a_truck": "yuyuy1233",
		"eta_a_trailer": "-",
		"eta_d_date": "28-10-20",
		"eta_d_time": "09:30",
		"eta_d_slot_time": "15:30",
		"port_out": "Port",
		"eta_d_3rd_party": "East",
		"place_to": "Stockholm",
		"eta_d_show_docs": "YES",
		"eta_d_driver": "-",
		"eta_d_driver_phone": "-",
		"eta_d_truck": "-",
		"eta_d_trailer": "-",
		"split_load": "NO",
		"trip_no": "24680",
		"loading_no": "24680",
		"etra_loading_time": "2",
		"is_area_blocked": "YES",
		"plumb_seal": "YES",
		"plumb_number": "567890",
		"is_etra_time_billable": "YES",
		"area": "CPH",
		"label_source": "PORT",
		"label": "LABEL456"
	},
	{
		"customer": "Valinton sea",
		"reference": "df123456",
		"service": "Load Truck - Warehouse - Conveyor",
		"status": "ON HOLD",
		"priority": "YES",
		"autocomplete": "YES",
		"terminal": "WARSAW",
		"eta_a_date": "30-10-20",
		"eta_a_time": "11:45",
		"eta_a_slot_time": "17:45",
		"port_in": "Warehouse",
		"eta_a_3rd_party": "West",
		"place_from": "Krakow",
		"eta_a_show_docs": "YES",
		"eta_a_driver": "-",
		"eta_a_driver_phone": "-",
		"eta_a_truck": "-",
		"eta_a_trailer": "13123ASDAD",
		"eta_d_date": "30-10-20",
		"eta_d_time": "11:45",
		"eta_d_slot_time": "17:45",
		"port_out": "Warehouse",
		"eta_d_3rd_party": "West",
		"place_to": "Poznan",
		"eta_d_show_docs": "YES",
		"eta_d_driver": "-",
		"eta_d_driver_phone": "-",
		"eta_d_truck": "-",
		"eta_d_trailer": "-",
		"split_load": "YES",
		"trip_no": "112233",
		"loading_no": "112233",
		"etra_loading_time": "43",
		"is_area_blocked": "NO",
		"plumb_seal": "NO",
		"plumb_number": "11223344",
		"is_etra_time_billable": "NO",
		"area": "WAW",
		"label_source": "WAREHOUSE",
		"label": "LABEL789"
	},
	{
		"customer": "Vojager fish",
		"reference": "df234567",
		"service": "Unload Ship - Dock - Crane",
		"status": "IN TRANSIT",
		"priority": "NO",
		"autocomplete": "YES",
		"terminal": "HELISNKI",
		"eta_a_date": "02-11-20",
		"eta_a_time": "13:15",
		"eta_a_slot_time": "19:15",
		"port_in": "Dock",
		"eta_a_3rd_party": "North",
		"place_from": "Tallinn",
		"eta_a_show_docs": "NO",
		"eta_a_driver": "Vali",
		"eta_a_driver_phone": "-",
		"eta_a_truck": "-",
		"eta_a_trailer": "-",
		"eta_d_date": "03-11-20",
		"eta_d_time": "10:30",
		"eta_d_slot_time": "16:30",
		"port_out": "Dock",
		"eta_d_3rd_party": "North",
		"place_to": "Riga",
		"eta_d_show_docs": "YES",
		"eta_d_driver": "-",
		"eta_d_driver_phone": "-",
		"eta_d_truck": "-",
		"eta_d_trailer": "-",
		"split_load": "NO",
		"trip_no": "345678",
		"loading_no": "345678",
		"etra_loading_time": "123",
		"is_area_blocked": "YES",
		"plumb_seal": "YES",
		"plumb_number": "9876543",
		"is_etra_time_billable": "NO",
		"area": "HEL",
		"label_source": "DOCK",
		"label": "LABEL101112"
	},
	{
		"customer": "Maintance",
		"reference": "df345678",
		"service": "Ship Container - Port - Forklift",
		"status": "DELIVERED",
		"priority": "YES",
		"autocomplete": "NO",
		"terminal": "OSAKA",
		"eta_a_date": "05-11-20",
		"eta_a_time": "15:45",
		"eta_a_slot_time": "21:45",
		"port_in": "Port",
		"eta_a_3rd_party": "East",
		"place_from": "Tokyo",
		"eta_a_show_docs": "YES",
		"eta_a_driver": "-",
		"eta_a_driver_phone": "-",
		"eta_a_truck": "KIIIS1123",
		"eta_a_trailer": "HH313",
		"eta_d_date": "06-11-20",
		"eta_d_time": "12:00",
		"eta_d_slot_time": "18:00",
		"port_out": "Port",
		"eta_d_3rd_party": "East",
		"place_to": "Kyoto",
		"eta_d_show_docs": "YES",
		"eta_d_driver": "-",
		"eta_d_driver_phone": "-",
		"eta_d_truck": "-",
		"eta_d_trailer": "-",
		"split_load": "NO",
		"trip_no": "567890",
		"loading_no": "567890",
		"etra_loading_time": "5",
		"is_area_blocked": "YES",
		"plumb_seal": "NO",
		"plumb_number": "1234567",
		"is_etra_time_billable": "YES",
		"area": "OSA",
		"label_source": "PORT",
		"label": "LABEL131415"
	},
	{
		"customer": "Load fish",
		"reference": "df456789",
		"service": "Unload Ship - Dock - Conveyor",
		"status": "ON HOLD",
		"priority": "YES",
		"autocomplete": "YES",
		"terminal": "ROTTERDAM",
		"eta_a_date": "08-11-20",
		"eta_a_time": "09:30",
		"eta_a_slot_time": "15:30",
		"port_in": "Dock",
		"eta_a_3rd_party": "West",
		"place_from": "Amsterdam",
		"eta_a_show_docs": "NO",
		"eta_a_driver": "-",
		"eta_a_driver_phone": "-",
		"eta_a_truck": "-",
		"eta_a_trailer": "-",
		"eta_d_date": "08-11-20",
		"eta_d_time": "09:30",
		"eta_d_slot_time": "15:30",
		"port_out": "Dock",
		"eta_d_3rd_party": "West",
		"place_to": "Antwerp",
		"eta_d_show_docs": "YES",
		"eta_d_driver": "-",
		"eta_d_driver_phone": "-",
		"eta_d_truck": "-",
		"eta_d_trailer": "-",
		"split_load": "YES",
		"trip_no": "678901",
		"loading_no": "678901",
		"etra_loading_time": "6",
		"is_area_blocked": "NO",
		"plumb_seal": "YES",
		"plumb_number": "2345678",
		"is_etra_time_billable": "NO",
		"area": "ROT",
		"label_source": "DOCK",
		"label": "LABEL161718"
	},
	{
		"customer": "Norway",
		"reference": "df567890",
		"service": "Load Truck - Warehouse - Forklift",
		"status": "IN TRANSIT",
		"priority": "NO",
		"autocomplete": "YES",
		"terminal": "COPENHAGEN",
		"eta_a_date": "11-11-20",
		"eta_a_time": "11:00",
		"eta_a_slot_time": "17:00",
		"port_in": "Warehouse",
		"eta_a_3rd_party": "South",
		"place_from": "Malmo",
		"eta_a_show_docs": "YES",
		"eta_a_driver": "-",
		"eta_a_driver_phone": "-",
		"eta_a_truck": "-",
		"eta_a_trailer": "-",
		"eta_d_date": "11-11-20",
		"eta_d_time": "11:00",
		"eta_d_slot_time": "17:00",
		"port_out": "Warehouse",
		"eta_d_3rd_party": "South",
		"place_to": "Gothenburg",
		"eta_d_show_docs": "NO",
		"eta_d_driver": "-",
		"eta_d_driver_phone": "-",
		"eta_d_truck": "-",
		"eta_d_trailer": "-",
		"split_load": "NO",
		"trip_no": "789012",
		"loading_no": "789012",
		"etra_loading_time": "12",
		"is_area_blocked": "YES",
		"plumb_seal": "NO",
		"plumb_number": "8901234",
		"is_etra_time_billable": "YES",
		"area": "CPH",
		"label_source": "WAREHOUSE",
		"label": "LABEL192021"
	}
];

export const initialFakeOrderData = fakeOrdersData[0];